{
    'name': 'PAM ERP - Accounting',
    'version': '2.0',
    'summary': 'Accounting Module for Indonesian Water Industry',
    'description': """

PAM ERP - Accounting 1.0
==============================

Accounting Module for Indonesian Water Industry
copyright 2019

    """,
    'author': 'PT. Pastimakmur Kencana',
    'website': 'http://',
    'category': 'PAM',
    'sequence': 0,
    'depends': [
                'base',
                'mail',
                'hr',
                'web_fontawesome',
                # 'dash_board_highcharts'
                ],
    'demo': [],
    'data': [
        'views/pam_coa_type_views.xml',
        'views/pam_coa_ref_views.xml',
        'views/pam_coa_views.xml',
        'views/pam_balance_views.xml',
        'views/pam_bank_views.xml',
        'views/pam_vendor_views.xml',
        'views/journal_dashboard_views.xml',
        'views/pam_journal_entry_views.xml',
        'views/pam_journal_voucher_views.xml',
        'views/pam_journal_voucher_template.xml',
        'views/pam_journal_voucher_payment_views.xml',
        'views/pam_journal_entry_sequence.xml',
        'views/pam_journal_payment_views.xml',
        'views/pam_approval_hierarchy_views.xml',
        'views/pam_cashflow_views.xml',
        'views/pam_cashflow_sequence.xml',
        'views/pam_budget_views.xml',
        # 'views/pam_budget_department_views.xml',
        # 'views/pam_budget_views.xml',
        'views/pam_budget_entry_views.xml',
        'views/pam_customer_classification_views.xml',
        'views/pam_forecast_customer_views.xml',
        'views/pam_forecast_other_views.xml',
        'views/pam_budget_change_views.xml',
        'views/pam_budget_revision_views.xml',
        # 'views/pam_assumption_type_views.xml',
        'views/pam_closing_views.xml',
        'views/pam_open_views.xml',
        'views/pam_asset_journaling_views.xml',
        'views/pam_asset_group_pay_views.xml',
        'views/pam_report_type_views.xml',
        'views/pam_report_configuration_views.xml',
        # 'views/pam_depreciation_views.xml',
        'views/pam_asset_views.xml',
        'views/pam_asset_depreciation_views.xml',
        'views/pam_asset_reduction_views.xml',
        'views/pam_asset_subtraction_views.xml',
        'views/pam_asset_subtraction_sequence.xml',
        'views/pam_asset_category_views.xml',
        'views/pam_asset_item_views.xml',
        'views/pam_code_iso_views.xml',
        'views/pam_report_month_views.xml',
        'views/pam_water_account_views.xml',
        'views/pam_report_log_views.xml',
        'wizard/pam_budget_generate_wizard_views.xml',
        'wizard/pam_asset_wizard_views.xml',
        'wizard/pam_asset_depreciation_wizard_views.xml',
        'report/report_template_style.xml',
        'report/pam_journal_recap_report_views.xml',
        'report/pam_journal_recap_report_template.xml',
        'report/pam_journal_verification_report_views.xml',
        'report/pam_journal_verification_report_template.xml',
        'report/pam_ledger_recap_report_views.xml',
        'report/pam_ledger_recap_report_template.xml',
        'report/pam_ledger_report_views.xml',
        'report/pam_ledger_report_template.xml',
        'report/pam_balance_sheet_report_views.xml',
        'report/pam_balance_sheet_report_template.xml',
        'report/pam_profit_loss_report_views.xml',
        'report/pam_cash_flow_report_views.xml',
        'report/pam_cash_flow_report_template.xml',
        'report/pam_cash_turnover_report_views.xml',
        'report/pam_cash_turnover_report_template.xml',
        'report/pam_cost_breakdown_report_views.xml',
        'report/pam_cost_breakdown_report_template.xml',
        'report/pam_financial_aspect_report_views.xml',
        'report/pam_financial_aspect_report_template.xml',
        'report/pam_profit_loss_report_template.xml',
        'report/pam_co_recap_report_views.xml',
        'report/pam_co_recap_report_template.xml',
        'report/pam_co_daily_report_views.xml',
        'report/pam_co_daily_report_template.xml',
        'report/pam_detail_dhhd_open_report_views.xml',
        'report/pam_detail_dhhd_open_report_template.xml',
        'report/pam_ap_open_report_views.xml',
        'report/pam_ap_open_report_template.xml',
        'report/pam_asset_recap_report_views.xml',
        'report/pam_asset_recap_report_template.xml',
        'report/pam_journal_payment_report_template.xml',
        'report/pam_operational_summary_report_views.xml',
        'report/pam_operational_summary_report_template.xml',
        'report/pam_sak_etap_report_views.xml',
        'report/pam_sak_etap_report_template.xml',
        'report/pam_depreciation_report_views.xml',
        'report/pam_depreciation_report_template.xml',
        'report/pam_budget_income_report_views.xml',
        'report/pam_budget_cost_report_views.xml',
        'report/pam_budget_appk_report_views.xml',
        'report/pam_cash_flow_indirect_report_views.xml',
        'report/pam_cash_flow_indirect_report_template.xml',
        'data/pam.coa.type.csv',
        'data/pam.coa.csv',
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/pam_accounting_menu.xml',
    ],
    'qweb': [
        'static/src/xml/journal_dashboard.xml'
    ],
    'application': True,
}
# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
